import type { Metadata } from "next";
import "./globals.css";
import { sarabun } from "./fonts";
import AppHeader from "@/components/app/AppHeader";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={sarabun.className}>
        <AppHeader />
        {children}
      </body>
    </html>
  );
}
