import type { Metadata } from "next";
import "@/app/globals.css";
import { sarabun } from "@/app/fonts";
import AppHeader from "@/components/app/AppHeader";

export const metadata: Metadata = {
    title: "E-commerce System",
    description: "Generated by create next app",
};

export default function FrontLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <>
            <AppHeader />
            {children}
        </>
    );
}
